# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(choices=[(b'raebareli', b'Raebareli'), (b'lucknow', b'Lucknow'), (b'new delhi', b'New Delhi')], max_length=120),
        ),
    ]
