# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20171125_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Available',
            field=models.BooleanField(default=True),
        ),
    ]
