# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_products_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='ProductImage',
            field=models.ImageField(default=b'shop/None/default.png', height_field=b'heightField', upload_to=shop.models.upload_location, width_field=b'widthField'),
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(default=b'description of product'),
        ),
    ]
