# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20171125_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ProductImage',
            field=models.ImageField(default=b'shop/None/default.png', upload_to=shop.models.upload_location),
        ),
    ]
