# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20171125_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='catImg',
            field=models.FileField(default='catImg/None/default.svg', upload_to='catImg/'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(choices=[('raebareli', 'Raebareli'), ('lucknow', 'Lucknow'), ('new delhi', 'New Delhi')], max_length=120),
        ),
        migrations.AlterField(
            model_name='city',
            name='cityImg',
            field=models.ImageField(default='cityImg/None/default.png', height_field='heightField', upload_to='cityImg/', width_field='widthField'),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.CharField(default='india', max_length=120),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.CharField(choices=[('uttar_pradesh', 'Uttar Pradesh'), ('delhi', 'Delhi')], max_length=120),
        ),
        migrations.AlterField(
            model_name='products',
            name='ProductImage',
            field=models.ImageField(default='shop/None/default.png', upload_to=shop.models.upload_location),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(default='description of product'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='bannerImage',
            field=models.ImageField(default='shop/None/default.png', height_field='heightField', upload_to=shop.models.upload_location, width_field='widthField'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='closingDay',
            field=models.CharField(choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('None', 'none')], max_length=250),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subCatImg',
            field=models.FileField(default='subCatImg/None/default.png', upload_to='subCatImg/'),
        ),
    ]
