# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20171206_0521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('city',), 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterField(
            model_name='city',
            name='cityImg',
            field=models.ImageField(default='cityImg/default.png', height_field='heightField', upload_to='cityImg/', width_field='widthField'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='bannerImage',
            field=models.ImageField(default='shop/defaultimage/default.png', height_field='heightField', upload_to=shop.models.upload_location, width_field='widthField'),
        ),
    ]
