# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20180119_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='closingDay',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('None', 'none')], max_length=61),
        ),
        migrations.AlterField(
            model_name='shop',
            name='isActive',
            field=models.BooleanField(default=0),
        ),
    ]
