# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 18:57
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20180120_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='closingDay',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Sunday', 'sunday'), ('Monday', 'monday'), ('Tuesday', 'tuesday'), ('Wednesday', 'wednesday'), ('Thursday', 'thursday'), ('Friday', 'friday'), ('saturday', 'Saturday'), ('none', 'None')], max_length=61),
        ),
    ]
